---
- name: Install deps
  apt:
    name:
      - nvidia-driver-455
      - libnvidia-compute-455
      - libnvidia-encode-455
    state: present

- name: Remove obsolete nvenc gstreamer plugin
  file:
    path: /usr/local/lib/gstreamer-1.0/libgstnvenc.so
    state: absent
