---
- name: Provision woke server
  hosts: wokeserver
  remote_user: ansible
  become: yes
  roles:
    - base
    - gstreamer-nvenc
    - geerlingguy.nodejs
    - streamwall
    - streambackup


- name: Set up anchorbot
  hosts: anchorbot
  remote_user: ansible
  become: yes
  tags: anchorbot
  roles:
    - base
    - anchorbot

- name: Set up tinycount
  hosts: tinycount
  remote_user: ansible
  become: yes
  tags: tinycount
  roles:
    - base
    - tinycount

- name: Set up matrixproxy
  hosts: matrixproxy
  remote_user: ansible
  become: yes
  tags: matrixproxy
  roles:
    - base
    - geerlingguy.nodejs
    - matrixproxy

- name: Setup netdata
  hosts: wokeserver
  remote_user: ansible
  become: yes
  tags: netdata
  roles:
    - netdata
