- name: Remove hlsoutput script
  file:
    path: /home/streamwall/hlsoutput.sh
    state: absent

- name: Disable hlsoutput service
  systemd:
    name: hlsoutput
    enabled: no
    state: stopped
    scope: user
  register: disable_hlsoutput_result
  failed_when: "disable_hlsoutput_result is failed and 'Could not find the requested service' not in disable_hlsoutput_result.msg"
  become: yes
  become_user: streamwall

- name: Remove hlsoutput service file
  file:
    path: "{{ user_service_dir }}/hlsoutput.service"
    state: absent
  notify:
    - Reload user systemd

- name: Remove HLS data directory
  file:
    path: "{{ hls_output_path }}"
    state: absent
