---
- name: Remove rtmpoutput script
  file:
    path: /home/streamwall/rtmpoutput.sh
    state: absent

- name: Disable RTMP outputs
  systemd:
    name: "rtmpoutput-{{ item.name }}"
    enabled: no
    state: stopped
    scope: user
  register: disable_rtmpoutput_result
  failed_when: "disable_rtmpoutput_result is failed and 'Could not find the requested service' not in disable_rtmpoutput_result.msg"
  become: yes
  become_user: streamwall
  loop: "{{ stream_rtmp_destinations }}"
  loop_control:
    label: "{{ item.name }}"

- name: Remove rtmpoutput service file
  file:
    path: "{{ user_service_dir }}/rtmpoutput-{{ item.name }}.service"
    state: absent
  loop: "{{ stream_rtmp_destinations }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Reload user systemd
