---
- name: Remove streamcapture script
  file:
    path: /home/streamwall/streamcapture.sh
    state: absent

- name: Disable streamcapture service
  systemd:
    name: streamcapture
    enabled: no
    state: stopped
    scope: user
  register: disable_streamcapture_result
  failed_when: "disable_streamcapture_result is failed and 'Could not find the requested service' not in disable_streamcapture_result.msg"
  become: yes
  become_user: streamwall

- name: Remove streamcapture service file
  file:
    path: "{{ user_service_dir }}/streamcapture.service"
    state: absent
  notify:
    - Reload user systemd
