---
- name: Install streamdelay dependencies
  apt:
    name:
      - libgstreamer1.0-0
      - libgstreamer1.0-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-tools
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - swh-plugins

- name: Install shaka-packager
  get_url:
    url: https://github.com/google/shaka-packager/releases/download/v2.4.3/packager-linux
    dest: /home/streamwall/packager-linux
    mode: u+rwx
    checksum: sha256:22365c83d4fad5b1a0a228f4bf2dcbb7f449d1d02b45426813b2a5e29ca3d164
  become: yes
  become_user: streamwall

- name: Create IPC directory
  file:
    path: /home/streamwall/ipc
    state: directory
    owner: streamwall
    group: streamwall

- name: Create IPC FIFOs
  command: mkfifo -m 660 /home/streamwall/ipc/{{ item }}
  args:
    creates: /home/streamwall/ipc/{{ item }}
  loop:
    - packager-opus
    - packager-aac
    - packager-vp9-1080
    - packager-vp9-720
    - packager-vp9-480
    - packager-vp9-360
    - packager-h264-1080
    - packager-h264-720
    - packager-h264-480
    - packager-h264-360
  become: yes
  become_user: streamwall

- name: Create live stream data directory
  file:
    path: /home/streamwall/live
    state: directory
    owner: streamwall
    group: streamwall

- name: Update streamdelay repo
  git:
    repo: https://github.com/streamwall/streamdelay.git
    dest: /home/streamwall/streamdelay
    version: release
    update: yes
    force: yes
  become: yes
  become_user: streamwall
  register: streamdelay_repo

- name: Install streamdelay npm deps
  npm:
    path: /home/streamwall/streamdelay
    ci: yes
  become: yes
  become_user: streamwall
  when: streamdelay_repo.changed

- name: Write streamdelay config
  template:
    src: streamdelay.config.toml.j2
    dest: "{{ streamdelay_config_path }}"
    owner: streamwall
    group: streamwall

- name: Add streamdelay service file
  template:
    src: streamdelay.service.j2
    dest: "{{ user_service_dir }}/streamdelay.service"
    owner: streamwall
    group: streamwall
  notify:
    - Reload user systemd
    - Enable streamdelay
